djangoProjectcofe/djangoProjectcofe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls'))
]

djangoProjectcofe/landingpage/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from djangoProjectcofe import settings
app_name='landingpage'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('ab/', About.as_view(), name='about'),
    path('co/', Contactus.as_view(), name='contactus'),
    path('or/', OrderList.as_view(), name='orderlist'),
    path('me/', Menu.as_view(), name='menu'),
]

djangoProjectcofe/landingpage/models.py
from django.db import models
from .validators import price_menu_validator
from django.utils.translation import gettext


# Create your models here.

class Table(models.Model):
    number = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    status = models.CharField(max_length=100)


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"


class MenuItem(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False,
                            help_text='enter menu item name')
    price = models.IntegerField(help_text='enter the price',
                                verbose_name='price(ir)',
                                validators=[price_menu_validator])  # maxlenght nadin
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='category')
    discount = models.IntegerField(null=True, blank=True, verbose_name='takhfifat')
    serving_time_period = models.IntegerField()
    estimated_cooking_time = models.IntegerField()
    image = models.FileField(help_text='enter pic', verbose_name='menu image ', upload_to='menu_items/images/',
                             blank=True, null=True)
    creat_timestamp = models.DateTimeField(verbose_name='time creat', auto_now_add=True, null=True)  # زمان ساخت
    modify_timestamp = models.DateTimeField(auto_now=True, null=True, verbose_name='time edit')  # زمان ادیت

    def __str__(self):
        return f"{self.id}# {self.name}:{self.price}"


class Order(models.Model):
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    status = models.CharField(max_length=50)
    number = models.IntegerField()
    date_time_stamp = models.DateTimeField()

    # time_time_stamp = models.TimeField()

    def __str__(self):
        return f"{self.number}"


class OrderMenuItem(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    menu_item_id = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.order_id}-{self.menu_item_id}"


class Receipt(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    total_price = models.IntegerField()
    final_price = models.IntegerField()
    date_time_stamp = models.DateTimeField()

    # time_time_stamp = models.TimeField()

    def __str__(self):
        return f"{self.order_id}"

djangoProjectcofe/landingpage/views.py
from django.shortcuts import render
from .models import *
# Create your views here.
from django.views import generic, View
from django.utils.translation import gettext as _

# def landingview(request):
#     return render(request,'landingpage/landing_home.html')
#
# def landingview_hom(request):
#     return render(request,'landingpage/landing_about.html')

class Home(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'landingpage/landing_home.html')
    # template_name = 'landingpage/landing_home.html'


class About(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'landingpage/landing_about.html')
    # template_name = 'landingpage/landing_about.html'


class OrderList(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'landingpage/landing_orderlist.html')
    # template_name = 'landingpage/landing_order_list.css'


class Contactus(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'landingpage/landing_contactus.html')
    # template_name = 'landing_page/contact_us.css'


class Menu(generic.View):
    def get(self, request, *args, **kwargs):
        return render(request, 'landingpage/landing_menu.html')

    template_name = 'landing_page/menu.css'

    # def get(self, *args, **kwargs):
    #     context = super().get(*args, **kwargs)
    #     context['category'] = Category.objects.all()
    #     context['menuitem'] = MenuItem.objects.all()
    #     return context

djangoProjectcofe/templates/landingpage/landing_about.html
{% extends 'landingpage/landing_base.html' %}
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% block extra_head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'landing_page/about.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
    <title>{% trans 'cofe' %} </title>
{% endblock %}
{% block main %}
<div class="header">
    <div class="man">
        <h1>{% trans 'about us . .'%}</h1>
        <p>
            {% trans 'A small cup in tehran'%} <br>
            {% trans 'A cup of black coffee'%}<br>
            <br>{% trans 'TypeHot or ice-cold (usually hot) Region of origin'%}
            {% trans 'Horn of Africa[1] and South Arabia[2] Introduced 15th century'%}<br>
            {% trans 'Color Black, dark brown, light brown, beige'%}<br>
            {% trans 'Coffee is a brewed drink prepared from roasted coffee beans,'%}<br>
            {% trans ' the seeds of berries from certain Coffe aspecies.'%}<br>
            {% trans 'All fruit must be further processed from a raw material—the fruit and seed—into a stable,'%}<br>
            {% trans 'raw product; un-roasted, green coffee. To process the berries,'%}<br>
            {% trans ' the seed is separated from the fruit to produce green coffee'%}.<br>
            <br><br>
        </p>

        <ul class="sci">
            <li><a href="#"><img src="{% static 'landing_page/facebook.png' %}"></a></li>
            <li><a href="#"><img src="{% static 'landing_page/twitter.png' %}"></a></li>
            <li><a href="#"><img src="{% static 'landing_page/instagram.png' %}"></a></li>
        </ul>
    </div>
</div>

{% endblock %}
</html>

djangoProjectcofe/templates/landingpage/landing_base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans 'Cafe'  %}</title>
    <link href="{% static 'landing_page/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'landing_page/landing_base_css.css' %}" rel="stylesheet">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/5.0.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'landing_page/home.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
    <link href="https://static.neshan.org/sdk/openlayers/5.3.0/ol.css" rel="stylesheet" type="text/css">
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script type="text/javascript" src="https://static.neshan.org/sdk/openlayers/5.3.0/ol.js"></script>
    <style>
        body, h1, h2, h3, h4, h5 {
            font-family: "Raleway", sans-serif

        }
    </style>
</head>
<body style="background-color:lightyellow;z-index: 99">
<div class="container-fluid">

    <!--    Header-->
    <div style="position: sticky;top: 0;z-index: 99" class="row">
        <form class="h_button" action="{% url 'landingpage:home' %} " method="get">
            {{ form.as_P }}
            {% csrf_token %}
            <input class="h_button" type="submit" value="Home">
        </form>
        <form class="h_button" action="{% url 'landingpage:about' %} " method="get">
            {{ form.as_P }}
            {% csrf_token %}
            <input class="h_button" type="submit" value="About">
        </form>
         <form class="h_button" action="{% url 'landingpage:contactus' %} " method="get">
            {{ form.as_P }}
            {% csrf_token %}
            <input class="h_button" type="submit" value="CONTACT US">
        </form>
         <form class="h_button" action="{% url 'landingpage:menu' %} " method="get">
            {{ form.as_P }}
            {% csrf_token %}
            <input class="h_button" type="submit" value="MENU">
        </form>
         <form class="h_button" action="{% url 'landingpage:orderlist' %} " method="get">
            {{ form.as_P }}
            {% csrf_token %}
            <input class="h_button" type="submit" value="ORDER LIST">
        </form>

    </div>

    <!--    Body-->
    <div class="row" id="content">
        {% block main %}{% endblock %}

    </div>

    <!--    Footer-->
    <div class="row footer">

        <p style="margin-top: 2rem; color: white">Produced By <a href="https://github.com/amirrezakiani081">S.A.H.A</a>
        </p>
    </div>
</div>
{#<script>#}
{#    function content_include(name) {#}
{#        $.get("{{ url_for('page_content') }}", {'name': name}, function (response) {#}
{#            $('#content').html('')#}
{#            $('#content').html(response)#}
{#        })#}
{#    }#}
{#</script>#}
</body>
</html>

djangoProjectcofe/templates/landingpage/landing_contactus.html
{% extends 'landingpage/landing_base.html' %}
{% load i18n %}
{% load static %}
{% block extra_head %}
<meta charset="UTF-8">
<title>{% trans 'Cafe-'%}{% block title %}{% endblock %}</title>

<link href="{% static 'landing_page/contact_us.css' %}" rel="stylesheet">
<meta content="width=device-width, initial-scale=1" name="viewport">
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!--neshan-->
<link href="https://static.neshan.org/sdk/openlayers/5.3.0/ol.css" rel="stylesheet" type="text/css">
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
<script type="text/javascript" src="https://static.neshan.org/sdk/openlayers/5.3.0/ol.js"></script>
{% endblock %}

{% block main %}
<div style="background-color: lightyellow; align-content: center">
    <div class="container-fluid" style="color:white; background-color: lightyellow!important;">
        <div class="row">
            <div class="col-sm-8" style="position: center ; margin-left: auto ; margin-right: auto">
                <p style="margin-left: 250px; font-family: 'Consolas', 'Deja Vu Sans Mono', 'Bitstream Vera Sans Mono', monospace ; font-size: 20px; color: black">
                    {% trans 'Find us at the below location'%} </p></br>

                <div id="map"
                     style="position: relative; margin-left: 200px; width: 600px; height: 450px; background: #eee; border: 2px solid #aaa;"></div>


                <p class="col-8"
                   style="font-family: 'Consolas', 'Deja Vu Sans Mono', 'Bitstream Vera Sans Mono', monospace ; font-size: 20px ; margin-left: 200px; color: black">
                    <b>{% trans 'Expect More Than Coffee'%}</b></br>
                    {% trans 'We’re not just passionate purveyors of coffee, but everything else that goes with a full and'%}
                    {% trans 'rewarding coffeehouse experience. We also offer a selection of premium teas, fine pastries'%}
                    {% trans 'and other delectable treats to please the taste buds. And the music you hear in store is'%}
                    {% trans 'chosen for its artistry and appeal.'%}
                    {% trans 'It’s not unusual to see people coming to Starbucks to chat, meet up or even work. We’re a'%}
                    {% trans 'neighborhood gathering place, a part of the daily routine – and we couldn’t be happier about'%}
                    {% trans 'it. Get to know us and you’ll see: we are so much more than what we brew.'%}
                    {% trans 'We make sure everything we do is through the lens of humanity – from our commitment to the'%}
                    {% trans 'highest quality coffee in the world, to the way we engage with our customers and communities'%}
                    {% trans 'to do business responsibly.'%}
                </p></br>
            </div>
        </div>
    </div>
    <div class="container col-6">
        <div>
            <label for="fname"><b>First Name</b></label>
            <input type="text" id="fname" name="firstname" placeholder="Your name..">
            <label for="lname"><b>Last Name</b></label>
            <input type="text" id="lname" name="lastname" placeholder="Your last name..">
            <label for="email"><b>E-mail</b></label>
            <input type="text" id="email" name="email" placeholder="Your E-mail..">
            <label for="subject"><b>Subject</b></label>
            <textarea id="subject" name="subject" placeholder="Your message.." style="height:200px"></textarea>
{#            <button class="btn_detail" onclick="send()">SEND</button>#}
        </div>
    </div>
</div>


{#<script type="text/javascript">#}
    {#function send() {#}
    {#    let f_name = $('#fname').val()#}
    {#    let l_name = $('#lname').val()#}
    {#    let email = $('#email').val()#}
    {#    let message = $('#subject').val()#}
    {#    if (!f_name) {#}
    {#        alert('first name is empty')#}
    {#        return 0;#}
    {#    }#}
    {#    if (!l_name) {#}
    {#        alert('last name is empty')#}
    {#        return 0;#}
    {#    }#}
    {#    if (!message) {#}
    {#        alert('message is empty')#}
    {#        return 0;#}
    {#    }#}
    {#    $.post("{{ url_for('page_content') }}", {#}
    {#        'name': 'Contact',#}
    {#        'first_name': f_name,#}
    {#        'last_name': l_name,#}
    {#        'email': email,#}
    {#        'message': message#}
    {#    }, function (response) {#}
    {#        $('#content').html('')#}
    {#        $('#content').html(response)#}
    {#    })#}
{#    }#}

{#    let myMap = new ol.Map({#}
{#        target: 'map',#}
{#        key: 'web.MItkfFMYZVw0CWPE5hERgJkjwQ4aDQS7qJFrntLb',#}
{#        maptype: 'dreamy',#}
{#        poi: true,#}
{#        traffic: false,#}
{#        view: new ol.View({#}
{#            center: ol.proj.fromLonLat([51.338076, 35.699756]),#}
{#            zoom: 14#}
{#        })#}
{#    })}#}
{#</script>#}
{% endblock %}

djangoProjectcofe/templates/landingpage/landing_home.html
{% extends 'landingpage/landing_base.html' %}
{% load i18n %}
{% load static %}

{% block extera_head %}
    <link rel="stylesheet" href="{% static 'landing_page/home.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
{% endblock %}

{% block main %}

<div class="container">
<header>
<a href="#" class="logo"><br>{% trans 'coffee sharif' %}</a>
</header>
<div class="banner">
    <video SRC="{% static 'landing_page/CAfevideo.mp4' %}" muted autoplay loop type="mp4"></video>
    <div class="textBox">
        <h2>{% trans 'In the heart of Tehran' %}</h2><br>
        <p> {% trans 'A gallery, café and lounge in the heart of Toronto’s creative downtown'%}<br>
            <br>{% trans 'Experience the best with us'%}
        </p><br>
        <a href="#">RESERV ONLINE </a>
    </div>
    <div class="videoBx">
        <video SRC="{% static 'landing_page/CAfevideo.mp4' %}" muted autoplay loop type="mp4"></video>
    </div>
    <ul class="sci">
        <li><a href="#"><img src="{% static 'landing_page/facebook.png' %}"></a></li>
        <li><a href="#"><img src="{% static 'landing_page/twitter.png' %}"></a> </li>
        <li><a href="#"><img src="{% static 'landing_page/instagram.png' %}"></a> </li>

    </ul>
</div>
</div>
{% endblock %}

djangoProjectcofe/templates/landingpage/landing_menu.html
{% extends 'landingpage/landing_base.html' %}
{% load i18n %}
{% load static %}

{% block extera_head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link href="{% static 'landing_page/menu.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/5.0.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function add_order(item , number){
            $.ajax({
                url: '/page_content?name=order_list',
                type: 'GET',
                data: {
                    "item": item,
                    "number": number,
                },
                success: function (data) {
                    console.log(data);
                }
            });
        }
   </script>

{% endblock %}
{% block main %}
    <div class="container bg-image">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center">
                    <h2>Menu</h2>
                    <p style="color: black">Menu page of group4 cafe project</p>
                </div>
            </div>
        </div>
{#        <div class="row">#}
{#            <div class="col-lg-12">#}
{#                <label for="table">Table</label>#}
{#                <select name="tables" id="table" style="margin-bottom: 1rem">#}
{#                    {% for table in tables %}#}
{#                        <option value="{{ table.number }}">{{ table.position }} - {{ table.number }}</option>#}
{#                    {% endfor %}#}
{#                </select>#}
{#            </div>#}
{#        </div>#}
        <div class="row">
            {% for category in categories %}
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="card" style="width: auto; margin-bottom: 20px">
                        <img class="card-img-top" src="{% static 'landing_page/coffee.jpg' %}"alt="COFFEE" height="300" width="700">
                        <div class="card-body">
                            <h4 class="card-title text-center">{{ category.name }} Menu</h4>
                            <div class="card-text text-center">full of delicious items</div>
                            <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#{{ category.name}}">See Menu</button>
                        </div>
                    </div>
                </div>
                <div class="modal fade position-absolute" id="{{ category.name}}" tabindex="-1" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" style="text-align: center">{{ category.name }}</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="modal-body">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Price</th>
                                            <th>Discount</th>
                                            <th>Number</th>
                                            <th>action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in menu_items%}
                                            {% if item.category.name == category.name %}
                                                <tr>
                                                    <td>{{ item.name}}</td>
                                                    <td>{{ item.price }} T</td>
                                                    <td>{{ item.discount }}</td>
                                                    <td><input type="number" name="number" style="width:40%" id="{{ item.id }}"></td>
                                                    <td><button class="btn btn-sm btn-primary" id="{{ item.name }}" onclick="add_order('{{ item.name }}', $('#{{ item.id }}').val())">Order</button></td>
                                                </tr>
                                            {% endif %}

                                        {% endfor %}
                                    </tbody>

                                </table>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn bg-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}

        </div>
    </div>

{% endblock %}

djangoProjectcofe/templates/landingpage/landing_orderlist.html
{% extends 'landingpage/landing_base.html' %}
{% load i18n %}
{% load static %}


{% block extera_head %}
    <link href={% static 'landing_page/landing_order_list.css' %}" rel=" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        function send(confirm , table_number){
            $.ajax({
                url: '/page_content?name=order_list',
                type: 'GET',
                data: {
                    'confirm': confirm,

                    'table-number': table_number
                },
                success: function (data) {
                    console.log(data);
                }
            });
        }
        function cancel(index){
            $.ajax({
                url: '/page_content?name=order_list',
                type: 'GET',
                data: {
                    'index': index
                },
                success: function (data){
                    console.log(data);
                }
            });
        }
    </script>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row" style="min-height: 1000px; background-color: #5c636a; border: solid black; border-radius: 10px;">
        {% for order in orders %}
            {% if order != None %}
                <div class="row order_box" id="{{ order.0.id}}">
                    <div class="col-4">{{ order.0.name }}</div>
                    <div class="col-2">Quantity: {{ order.1 }}</div>
                    <div class="col-5">waiting for cooking</div>
                    <div class="col-1"><button class="laghv_btn" onclick="($('#{{ order.0.id }}').remove()) && cancel({{ order.0.id}})"><h4>X</h4></button></div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="row order_box" style="background-color: white!important;">
{#        <div class="col-3">#}
{#            <select id="table-position">#}
{#                {% for table in tables %}#}
{#                    <option>{{ table.position }}</option>#}
{#                {% endfor %}#}
{#            </select>#}
{#        </div>#}
        <div class="col-6">
            <select id="table-number">
                {% for table in tables %}
                    {% if table.status == 0 %}
                        <option value={{ table.number }}>{{ table.number }} : {{ table.position }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>
        <div class="col-6">
            <button type="button" class="btn btn-dark" style="width: 100px" onclick="send('confirm', $('#table-number').val())">Send</button>
        </div>
    </div>

</div>


{% endblock %}